version: '3.9'

services:
    postgres:
        image: postgres:14
        # expose:
        #     - "5432"
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - db_volume:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            TZ: Europe/Lisbon
            PGTZ: Europe/Lisbon

    phoenix_dev:
        build:
            dockerfile: Dockerfile_dev
        image: phoenix_dev
        ports:
            - "4000:4000"
        volumes:
            - ./phoenix/chat_elixir:/home/app
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_DATABASE: ${POSTGRES_DATABASE}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            OPENAI_API_KEY: ${OPENAI_API_KEY}
            ERL_AFLAGS: -kernel shell_history enabled
        restart: always
        depends_on:
            - postgres

volumes: 
    db_volume: