import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :chat_elixir, ChatElixirWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  # To bust cache during hot upgrades
  version: Mix.Project.config()[:version]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: ChatElixir.Finch

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# Gigalixir config
config :chat_elixir, ChatElixirWeb.Endpoint,
  # Without this line, your app will not start the web server!
  server: true,
  # Needed for Phoenix 1.3. Doesn't hurt for other versions
  load_from_system_env: true,
  # Needed for Phoenix 1.2 and 1.4. Doesn't hurt for 1.3.
  http: [port: {:system, "PORT"}],
  secret_key_base: "${SECRET_KEY_BASE}",
  url: [host: "smartcrop.pt", port: 443],
  cache_static_manifest: "priv/static/cache_manifest.json",
  # To bust cache during hot upgrades
  version: Mix.Project.config()[:version]

config :chat_elixir, ChatElixir.Repo,
  adapter: Ecto.Adapters.Postgres,
  url: "${DATABASE_URL}",
  # Works around a bug in older versions of ecto. Doesn't hurt for other versions.
  database: "",
  ssl: true,
  # Free tier db only allows 4 connections. Rolling deploys need pool_size*(n+1) connections where n is the number of app replicas.
  pool_size: 2
